using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using EmployeeManager.Model.Interfaces;

namespace EmployeeManager.Model.BaseModel;

/// <summary>
/// Represents the base entity for all models in the EmployeeManager project.
/// This class provides common properties like Id, Name, and Active status.
/// </summary>
public class Entity : IEntity
{
    /// <summary>
    /// Gets or sets the unique identifier for the entity.
    /// The ID is automatically generated by the database upon creation.
    /// </summary>
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long Id { get; set; }

    /// <summary>
    /// Gets or sets the name of the entity.
    /// </summary>
    public string Name { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether the entity is active.
    /// This can be used to soft delete or deactivate entities without removing them from the database.
    /// </summary>
    public bool Active { get; set; }
}